core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('travel.urls'))
]

urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

travel/urls.py
from django.urls import path
from . import views
from .views import *

urlpatterns = [
    path('', views.home, name='home'),
    path('contact-us/',views.contacts , name="contact"),
    path('our-team/',views.teams, name= "team"),
    path('<str:slug>/',views.category , name="category"),
]

travel/models.py
from django.db import models
import itertools
from django.utils.text import slugify


# Create your models here.

class Category(models.Model):
  name = models.CharField(max_length=200)
  slug = models.SlugField(unique = True, null=True, blank=True)
  description = models.CharField(max_length= 1000 ,null = True)


  class Meta:
    verbose_name = "category"
    verbose_name_plural = "categories"

  def __str__(self):
      return self.name
  
  def _generate_slug(self):
        max_length = self._meta.get_field('slug').max_length
        value = self.name
        slug_candidate = slug_original = slugify(value, allow_unicode=True)
        for i in itertools.count(1):
            if not Category.objects.filter(slug=slug_candidate).exists():
                break
            slug_candidate = '{}-{}'.format(slug_original, i)

        self.slug = slug_candidate

  def save(self, *args, **kwargs):
      if not self.pk:
          self._generate_slug()

      super().save(*args, **kwargs)

class Sub_Category(models.Model):
  name = models.CharField(max_length=200)
  category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
  description = models.CharField(max_length= 1000, null = True)

  class Meta:
    verbose_name = "sub_category"
    verbose_name_plural = "sub_categories"

  def __str__(self):
    return self.name

class Specific_Category(models.Model):
  name = models.CharField(max_length=200)
  sub_category = models.ForeignKey(Sub_Category, on_delete=models.SET_NULL, null=True)
  description = models.CharField(max_length= 1000, null = True)

  class Meta:
    verbose_name_plural = "specific_categories"

  def __str__(self):
    return self.name





  

travel/views.py
from django.shortcuts import render
from .models import *
# Create your views here.

def home(request):
  primary_categories = Category.objects.order_by('id')[:5]
  remaining_categories = Category.objects.order_by('id')[5:]
  
  context = {
    'categories':primary_categories, 
    'rem_categories':remaining_categories
    }
  return render(request,'home/home.html', context)

def category(request ,slug):
  primary_categories = Category.objects.order_by('id')[:5]
  remaining_categories = Category.objects.order_by('id')[5:]
  category = Category.objects.filter(slug=slug)
  context = {
    'categories':primary_categories, 
    'rem_categories':remaining_categories,
    'category' : category
    }
  return render(request, 'category.html',context)

def contacts(request):

  context = {}
  return render(request, 'contact_us.html',context)

def teams(request):
  context = {range:range(1,7)}
  return render(request, 'our_team.html',context)

templates/category.html
{%extends 'main.html'%}{%load static%}
{%block css%}{%static 'css/category.css'%}{%endblock%}
{%block body%}


{%for category in category %}
<div class="">
  <div class="container">
  
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="clearfix" style="padding-bottom: 7px;">
            <h2 class="font-24">{{category.name}}</h2>
        </div>

        <div class="dtl_discription"> 
          <div class="trip_intr">
            <p style="text-align: justify;">{{category.description}}</p>
          </div>
        </div>

    </div>
  </div>
</div>

{% comment %} packages section {% endcomment %}
<div class="package_section">
  <div class="container">
    <div class="row clearfix">                                 <div class="col-xs-12 col-sm-6 col-md-4 col-50 mrgb-30">
                                  <div class="pakg_box">
                                    <div class="pakg_img"> 
                                    <a href="https://majestichimalaya.com/tour/nepal-tour-with-poon-hill3210m/">
                                      <img src=" https://majestichimalaya.com/wp-content/themes/majestic_himalaya/inc/timthumb.php?src=https://majestichimalaya.com/wp-content/uploads/2018/05/1-15.jpg&amp;w=360&amp;h=240" alt="Nepal Tour With Poon Hill Trek" width="100%">
                                    </a>
                                                                          <div class="price_btn">
                                        <h4>
                                          <span>All Inclusive </span> </h4>
                                      </div>
                                                                            <div class="title_btn">
                                        <h4>Nepal Tour With Poon Hill Trek</h4>
                                        <h5>13 Days</h5>
                                      </div>
                                    </div>
                                    <div class="pakg_discription">
                                      <p>This trip is very carefully designed covering all major touristic destinations in the country. In… <a href="https://majestichimalaya.com/tour/nepal-tour-with-poon-hill3210m/">More Details  »</a>
                                        
                                      </p>
                                    </div>
                                  </div>
                                </div> 
                                                              <div class="col-xs-12 col-sm-6 col-md-4 col-50 mrgb-30">
                                  <div class="pakg_box">
                                    <div class="pakg_img"> 
                                    <a href="https://majestichimalaya.com/tour/982/">
                                      <img src=" https://majestichimalaya.com/wp-content/themes/majestic_himalaya/inc/timthumb.php?src=https://majestichimalaya.com/wp-content/uploads/2017/11/p.jpg&amp;w=360&amp;h=240" alt="Lower Dolpo Trek" width="100%">
                                    </a>
                                                                          <div class="price_btn">
                                        <h4>
                                          <span>All Inclusive </span> </h4>
                                      </div>
                                                                            <div class="title_btn">
                                        <h4>Lower Dolpo Trek</h4>
                                        <h5>18 Days </h5>
                                      </div>
                                    </div>
                                    <div class="pakg_discription">
                                      <p>Lower Dolpo trek offers outstanding trekking experiences in the remote western part of Nepal. This… <a href="https://majestichimalaya.com/tour/982/">More Details  »</a>
                                        
                                      </p>
                                    </div>
                                  </div>
                                </div> 
                                                              <div class="col-xs-12 col-sm-6 col-md-4 col-50 mrgb-30">
                                  <div class="pakg_box">
                                    <div class="pakg_img"> 
                                    <a href="https://majestichimalaya.com/tour/annapurna-with-tilicho-lake-trek/">
                                      <img src=" https://majestichimalaya.com/wp-content/themes/majestic_himalaya/inc/timthumb.php?src=https://majestichimalaya.com/wp-content/uploads/2017/11/t.jpg&amp;w=360&amp;h=240" alt="Annapurna Circuit Trek with Tilicho Lake" width="100%">
                                    </a>
                                                                          <div class="price_btn">
                                        <h4>
                                          <span>All Inclusive </span> </h4>
                                      </div>
                                                                            <div class="title_btn">
                                        <h4>Annapurna Circuit Trek with Tilicho Lake</h4>
                                        <h5>18 Days </h5>
                                      </div>
                                    </div>
                                    <div class="pakg_discription">
                                      <p>Annapurna Circuit trek with Tilicho Lake is a fantastic journey along the famous Annapurna region… <a href="https://majestichimalaya.com/tour/annapurna-with-tilicho-lake-trek/">More Details  »</a>
                                        
                                      </p>
                                    </div>
                                  </div>
                                </div> 
                               </div>
  </div>
</div>

{%endfor%}
{%endblock%}

templates/contact_us.html
{%extends 'main.html'%}{%load static%}{%block css%}{%static 'css/contact_us.css'%}{%endblock%}
{%block body%}
<div class="container">
    <i>
    <ol class="breadcrumb">
        <span>You are here:</span>
            <li><a href="https://majestichimalaya.com">Home</a></li>
            
                        <li class="active">Contact Us</li>
                    </ol></i>
  </div>

<div class="">

            
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-8">
           <div class="contact_box">
             <div class="form_sec">
                <form class="well form-horizontal" action=" " method="post" id="contact_form">
                  <div role="form" class="wpcf7" id="wpcf7-f261-o1" lang="en-US" dir="ltr">
<div class="screen-reader-response"></div>

<div style="display: none;">
<input type="hidden" name="_wpcf7" value="261">
<input type="hidden" name="_wpcf7_version" value="4.9">
<input type="hidden" name="_wpcf7_locale" value="en_US">
<input type="hidden" name="_wpcf7_unit_tag" value="wpcf7-f261-o1">
<input type="hidden" name="_wpcf7_container_post" value="0">
</div>
<fieldset>
<h3 class="font-18 mrgb-20">Contact us</h3>
<div class="form-group"><label class="col-md-4 control-label">Full Name</label>
<div class="col-md-8 inputGroupContainer">
<div class="input-group"><span class="input-group-addon"><i class="fas fa-user"></i></span><span class="wpcf7-form-control-wrap textFirstName"><input type="text" name="textFirstName" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required form-control" aria-required="true" aria-invalid="false" placeholder="Full Name"></span></div>
</div>
</div>
<div class="form-group"><label class="col-md-4 control-label">E-Mail</label>
<div class="col-md-8 inputGroupContainer">
<div class="input-group"><span class="input-group-addon"><i class="fas fa-envelope"></i></span><span class="wpcf7-form-control-wrap email"><input type="email" name="email" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email form-control" aria-required="true" aria-invalid="false" placeholder="E-mail Address"></span></div>
</div>
</div>
<div class="form-group"><label class="col-md-4 control-label">Phone</label>
<div class="col-md-8 inputGroupContainer">
<div class="input-group"><span class="input-group-addon"><i class="fas fa-phone"></i></i></span><span class="wpcf7-form-control-wrap textPhoneNumber"><input type="text" name="textPhoneNumber" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required form-control" aria-required="true" aria-invalid="false" placeholder="977-9849800709"></span></div>
</div>
</div>
<div class="form-group"><label class="col-md-4 control-label">Address</label>
<div class="col-md-8 inputGroupContainer">
<div class="input-group"><span class="input-group-addon"><i class="fas fa-home"></i></span><span class="wpcf7-form-control-wrap textAddress"><input type="text" name="textAddress" value="" size="40" class="wpcf7-form-control wpcf7-text form-control" aria-invalid="false" placeholder="Address"></span></div>
</div>
</div>
<div class="form-group"><label class="col-md-4 control-label">Message</label>
<div class="col-md-8 inputGroupContainer">
<div class="input-group"><span class="input-group-addon"><i class="fas fa-pencil"></i></span><span class="wpcf7-form-control-wrap textareaProjectDescription"><textarea name="textareaProjectDescription" cols="40" rows="10" class="wpcf7-form-control wpcf7-textarea form-control" aria-invalid="false" placeholder="Message"></textarea></span></div>
</div>
</div>
<div class="form-group"><label class="col-md-4 control-label"></label>
<div class="col-md-8"><input type="submit" value="Send" class="wpcf7-form-control wpcf7-submit btn btn-warning widthbutton1"></div>
</div>
</fieldset>
<div class="wpcf7-response-output wpcf7-display-none"></div></div></form>                
             </div>
           </div>
       </div>
      
      <div class="col-xs-12 col-sm-6 col-md-4">
         
         <div class="wel_inner">
           <div class="cont_information mrgb-30">
              <h1 class="font-18">Contact Location</h1>
              <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3531.336329903988!2d85.38286411463895!3d27.737770482779286!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39eb1b32f0b1b125%3A0x39c8bac5c7e75c85!2sMajestic+Himalaya+Treks+%26+Expeditions!5e0!3m2!1sen!2snp!4v1525851980286" width="100%" height="480" frameborder="0" style="border:0" allowfullscreen=""></iframe>
            </div>
           
       </div>
      </div>
      
    </div>
  </div>
</div>
{%endblock%}

templates/footer.html
<div class="footer" id="footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-3">
        <div class="fot_info">
                  <h3 class="mrgb-20">Trekking</h3>
          <ul class="cnt_dtl mrgb-30">

          
           <li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Luxury Poon Hill Trek</a></li>
           
           <li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Annapurna Circuit Trek</a></li>
           
           <li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Everest View Trek</a></li>
           
           <li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Tamang Heritage Trail with Langtang</a></li>
           
           <li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Everest Gokyo Ri Trek</a></li>
           
           <li><a href=""><i class="fa fa-angle-right" aria-hidden="true"></i>Lower Dolpo Trek</a></li>
                      
            
          </ul>
                  </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-3">
        <div class="fot_info">
                  <h3 class="mrgb-20">Peak Climbing</h3>
          <ul class="cnt_dtl mrgb-30">

          
           <li><a href="https://majestichimalaya.com/tour/mera-peak-climbing/"><i class="fa fa-angle-right" aria-hidden="true"></i>Mera Peak Climbing</a></li>
           
           <li><a href="https://majestichimalaya.com/tour/island-peak-climbing-3/"><i class="fa fa-angle-right" aria-hidden="true"></i>Island Peak Climbing</a></li>
           
           <li><a href="https://majestichimalaya.com/tour/yala-peak-climbing/"><i class="fa fa-angle-right" aria-hidden="true"></i>Yala Peak Climbing</a></li>
           
           <li><a href="https://majestichimalaya.com/tour/lobuche-peak-climbing/"><i class="fa fa-angle-right" aria-hidden="true"></i>Lobuche East Peak Climbing</a></li>
           
           <li><a href="https://majestichimalaya.com/tour/mardi-himal-peak-climbing/"><i class="fa fa-angle-right" aria-hidden="true"></i>Mardi Himal Peak Climbing</a></li>
           
           <li><a href="https://majestichimalaya.com/tour/pisang-peak-climbing-2/"><i class="fa fa-angle-right" aria-hidden="true"></i>Pisang Peak Climbing</a></li>
           
           <li><a href="https://majestichimalaya.com/tour/chulu-west-peak-climbing/"><i class="fa fa-angle-right" aria-hidden="true"></i>Chulu West Peak Climbing</a></li>
                      
            
          </ul>
                  </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-3">
        <div class="fot_info">
                  <h3 class="mrgb-20">Helicopter Tours</h3>
          <ul class="cnt_dtl mrgb-30">

          
           <li><a href="https://majestichimalaya.com/tour/gosainkunda-helicopter-tour/"><i class="fa fa-angle-right" aria-hidden="true"></i>Gosainkunda Helicopter Tour</a></li>
           
           <li><a href="https://majestichimalaya.com/tour/langtang-helicopter-tour/"><i class="fa fa-angle-right" aria-hidden="true"></i>Langtang Helicopter Tour</a></li>
           
           <li><a href="https://majestichimalaya.com/tour/muktinath-helicopter-tour/"><i class="fa fa-angle-right" aria-hidden="true"></i>Muktinath Helicopter Tour</a></li>
           
           <li><a href="https://majestichimalaya.com/tour/upper-mustang-helicopter-tours/"><i class="fa fa-angle-right" aria-hidden="true"></i>Upper Mustang Helicopter Tour</a></li>
           
           <li><a href="https://majestichimalaya.com/tour/everest-base-camp-helicopter-tour/"><i class="fa fa-angle-right" aria-hidden="true"></i>Everest Base Camp Helicopter Tour</a></li>
           
           <li><a href="https://majestichimalaya.com/tour/annapurna-helicopter-tour/"><i class="fa fa-angle-right" aria-hidden="true"></i>Annapurna Helicopter Tour</a></li>
                      
            
          </ul>
                  </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-3">
        <div class="fot_info fot_infolst">
          <h3 class="mrgb-20">Contact info</h3>
          <ul class="cnt_dtl mrgb-30">
            <li><span><i class="fa fa-home" aria-hidden="true"></i>Majestic Himalaya</span></li>
            <li><span><i class="fa fa-fax" aria-hidden="true"></i>Post Box No, 9922,  Kathmandu</span></li>
            <li><span><i class="fa fa-phone" aria-hidden="true"></i>Phone:977-9849800709</span></li>
            <li><span><i class="fa fa-mobile" aria-hidden="true"></i>Cell Phone:977-9849800709,9851017589, 9843748609</span></li>
            <li><span><i class="fa fa-envelope" aria-hidden="true"></i>Email:info@majestichimalaya.com</span></li>
          </ul>
         
        </div>
      </div>
    </div>
  </div>
</div>

<div class="footer_last">
  <div class="container">
    <div class="fot_inner">
      <p>© 2021&nbsp;&nbsp;Majestic Himalaya.&nbsp; All Rights Reserved. &nbsp; | &nbsp; Powered By: <a href="#" target="_blank" style="color:#fff;"> Prodigy Technosys</a> </p>
    </div>
  </div>
</div>

templates/header.html
{% load static %} 
<header>
  <div class="container">
    <div class="row">

        <div class="col-xs-12 col-sm-5 col-md-5">
          <div class="logo">
            <a href="{%url 'home'%}" >
              <img src="{% static 'images/logo.png'%}" alt= "Travel App">
            </a>
          </div>
        </div>

        <div class="col-xs-6 col-sm-2 col-md-2 col-50 logo">
          <img src= "{%static  'images/visitnepal.png'%}" alt="Visit Nepal">
        </div>

        <div class="col-sm-5 col-md-5">
          <div class="header_detail m-3">
            <div class="header_info">
              <ul>
                <li><i class="fas fa-phone-alt"></i>9843584287</li>
                <li><i class="fas fa-envelope"></i>theabhi45@gmail.com</li>
              </ul>
            </div>
          </div>
          <div class="header_link">
            <ul>
              <ul class="nav navbar-right">
                  <li><a href="{%url 'team'%}">Our Team</a></li>
                  <li><a href="#">Become a partner</a></li>
                  <li><a href="{%url 'contact'%}">Contact Us</a></li>
              </ul>
            </ul>
          </div>
        </div>
    </div>
  </div>
</header>

templates/home/home.html
{% extends 'main.html' %} {%load static %}
{% block css %} {%static 'css/home.css'%} {% endblock css %}
{% block body %} 
{% comment %} Social linnks {% endcomment %}
<div class="hanging-social">
  <ul>
    <li class="facebook">
      <a href="#" target="_blank">
        <i class="fab fa-facebook"></i>
      </a>
    </li>
    <li class="twitter">
    <a href="#" target="_blank">
        <i class="fab fa-twitter"></i>
      </a>
    </li>
  
    <li class="instagram">
      <a href="" target="_blank">
        <i class="fab fa-instagram"></i>
      </a>
    </li>
    <li class="ta">
      <a href="#" target="_blank">
        <i class="fab fa-tripadvisor"></i>
      </a>
    </li>
  </ul>
</div>

{% comment %} Slider section {% endcomment %}
{%include 'home/slider.html'%}

{% comment %} WelcomeSection {% endcomment %}
{% include 'home/welcome_section.html'%}

{% endblock body %}

templates/home/slider.html
{%load static %}

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">

  <div class="carousel-inner">
    <div class="carousel-item active">
        <img class="d-block w-100" src="{%static 'images/boudhanath.jpeg'%}" alt="Third slide">
    </div>
    <div class="carousel-item ">
      <img class="d-block w-100" src="{%static 'images/lake.png'%}" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{%static 'images/skydiving.jpeg'%}" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{%static 'images/mountain.jpeg'%}" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>

  
</div>
<div class="test">
<div class="serchcont container">
    <div class="search">
      <h2>Find your tour</h2>
      <form method="POST">
        <div class="row">
          <div class="col-xs-5 col-sm-6 col-md-4">
            <div class="destination_select_field mrgb-10">
                <select class="form-control selectpicker text-light" data-live-search="true" name="destinations" required="">
                      <option value="1">You are from</option>
                                  </select>
                    <i class="fa fa-map-marker" aria-hidden="true"></i>
            </div>
          </div>
          <div class="col-xs-5 col-sm-6 col-md-3">
            <div class="Activities_select_field mrgb-10">
              <select class="form-control selectpicker text-light" data-live-search="true" name="activities" required="">
                    <option value="1">Activities</option>
                    <option value="adventurous-tours-in-nepal">Adventurous Tours in Nepal</option>
                    <option value="multi-country-tour">Multi Country Tours</option>
                    <option value="buddhistpilgrimage-tour">Buddhist Tours in Nepal</option>
                    <option value="popular-package">Most Selling</option>
                    <option value="helicopter-tours-in-nepal">Helicopter Tours in Nepal</option>
                    <option value="winter-summer-trekking-in-nepal">Christmas Tours in Nepal</option>
                    <option value="rafting-kayaking">River Rafting in Nepal</option>
                    <option value="major-festival-trips">Festival Tours in Nepal</option>
                    <option value="family-holidays">Nepal Family Holidays</option>
                    <option value="jungle-safari">Jungle Safaris in Nepal</option>
                    <option value="other-actitivies">More Activities</option>
                    <option value="lantang-region-trek">Lantang Region Treks</option>
                    <option value="annapurna-region-trek">Annapurna Region Treks</option>
                    <option value="everest-region-trekking">Everest Region Treks</option>
                    <option value="expedition">Expeditions in Nepal</option>
                    <option value="peak-climbing-in-nepal">Peak Climbing in Nepal</option>
                    <option value="trekking">Trekking in Nepal</option>
                </select>
                <i class="fa fa-angle-down" aria-hidden="true"></i>
            </div>
          </div>
          <div class="col-xs-5 col-sm-6 col-md-3">
            <div class="check_in_field mrgb-10">
              <input type="text" id="Check_out_date_tab" placeholder="check in" data-provide="datepicker" class="datepicker hasDatepicker">
              <i class="fa fa-calendar text-light"></i>
            </div>
          </div>
          <div class="col-xs-5 col-sm-6 col-md-2">
            <div class="submit_field mrgb-10">
                <input type="hidden" value="1" name="search-submit">
                <button class="btn tab_search" type="submit">Search</button>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
  </div>

templates/main.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,700,900" rel="stylesheet"> 
  <link rel="stylesheet" href="{%static 'css/fundamentals.css'%}">
  <link rel="stylesheet" href="{% block css %} {% endblock css %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <title>Travel app</title>
</head>
<body>
  {% comment %} Header & Navbar section {% endcomment %}
  {% include "header.html"%}
  {% include "navbar.html" %}


  {% comment %} Main body section {% endcomment %}
  {% block body %} {% endblock body %}

  {% comment %} Footer section {% endcomment %}
  {% include "footer.html" %}


  {%block js%} {%endblock%}
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark">
  <div class="container">
    <div class="navigation" >
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav m-auto">
          <li class="nav-item active">
            <a class="nav-link cat" href="{%url 'home'%}">Home </a>
          </li>
          {%for category in categories%}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle cat" href="{%url 'category' category.slug%}" id="navbarDropdown" role="button"  aria-haspopup="true" aria-expanded="false">
                {{category.name}}
              </a>
              {%if category.sub_category_set.all %}
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% comment %} sub category {% endcomment %}
              {%for sub in category.sub_category_set.all%} 
              <ul  style=" margin-left: 0px; margin-top: 0px; z-index: 1001; border-bottom: 0.5px solid grey;">
                <li>
                  <a class="dropdown-item sub" href="#" id="sub{{sub.id}}"  data-toggle="dropdown" >{{sub.name}}</a>
                  {%if sub.specific_category_set.all %}
                    <ul class="dropdown-menu " style="width: auto; top: auto; left: 0px; min-width: 10em; max-width: 20em;margin-left: 216.875px; margin-top: -43px; z-index: 1002; ">
                      {%for spec in sub.specific_category_set.all%}
                        <li class="dropdown" style="border-bottom: 0.5px solid grey;">
                            <a class="dropdown-item" data-toggle="dropdown" href="#">{{spec.name}}</a>
                        </li>
                      {%endfor%}
                    </ul>
                  {%endif%}  
                </li>
              </ul>
              {%endfor%} 
              
              
              {%endif%} 
            </li>
          {%endfor%}

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle cat" href="{{category.slug}}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              More Activities
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              {%for rem in rem_categories%}
                <a class="dropdown-item" href="#">
                {{rem.name}}
                </a>
              {%endfor%}
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav> 